name: null_safety_percentage
description: Command-line tool to provide null-safety percentage info of a project. Track your migration progress on mixed-version programs that execute with unsound null safety.
version: 1.0.0+3
homepage: https://www.github.com/dartsidedev/null_safety_percentage
repository: https://www.github.com/dartsidedev/null_safety_percentage
issue_tracker: https://www.github.com/dartsidedev/null_safety_percentage/issues
executables:
  null_safety_percentage: null_safety_percentage
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  build_pubspec: ^0.2.0+1
  build_runner: ^1.11.5
  lints: ^1.0.0
  test: ^1.16.0
  meta: ^1.7.0
dependencies:
  args: ^2.3.0
scripts: derry.yaml
